nodes:
  mongodb:
    type: mongodb
    uri: mongodb://localhost:57017
    namespace: test.restaurants
  elastic:
    type: elasticsearch
    uri: http://localhost:59200/
    namespace: test.restaurants
